<a href="https://colab.research.google.com/github/gichukia/My-First-Repo/blob/main/World_Cup_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Exploratory Data Analysis wirh World Cup 2022 data.**

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pylab as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('max_columns', 200)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Fifa_world_cup_matches.csv to Fifa_world_cup_matches.csv

In [3]:
df = pd.read_csv('/content/Fifa_world_cup_matches.csv')

Understanding the Data.

In [4]:
df.shape

(56, 88)

In [5]:
df.head(5)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,assists team1,assists team2,on target attempts team1,on target attempts team2,off target attempts team1,off target attempts team2,attempts inside the penalty area team1,attempts inside the penalty area team2,attempts outside the penalty area team1,attempts outside the penalty area team2,left channel team1,left channel team2,left inside channel team1,left inside channel team2,central channel team1,central channel team2,right inside channel team1,right inside channel team2,right channel team1,right channel team2,total offers to receive team1,total offers to receive team2,inbehind offers to receive team1,inbehind offers to receive team2,inbetween offers to receive team1,inbetween offers to receive team2,infront offers to receive team1,infront offers to receive team2,receptions between midfield and defensive lines team1,receptions between midfield and defensive lines team2,attempted line breaks team1,attempted line breaks team2,completed line breaksteam1,completed line breaks team2,attempted defensive line breaks team1,attempted defensive line breaks team2,completed defensive line breaksteam1,completed defensive line breaks team2,yellow cards team1,yellow cards team2,red cards team1,red cards team2,fouls against team1,fouls against team2,offsides team1,offsides team2,passes team1,passes team2,passes completed team1,passes completed team2,crosses team1,crosses team2,crosses completed team1,crosses completed team2,switches of play completed team1,switches of play completed team2,corners team1,corners team2,free kicks team1,free kicks team2,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,5,6,2,0,0,2,0,0,0,1,0,3,5,3,2,4,3,2,15,8,0,7,3,6,1,4,9,6,520,532,116,127,235,187,169,218,5,8,136,155,86,99,9,13,4,7,4,2,0,0,15,15,3,4,450,480,381,409,9,14,4,4,9,9,1,3,19,17,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,13,8,2,6,6,2,0,0,6,1,7,3,3,4,10,6,3,2,11,3,5,0,2,3,3,1,11,0,1061,212,207,53,386,86,468,73,16,4,238,101,178,45,25,7,16,4,0,2,0,0,9,14,2,2,809,224,730,154,23,8,7,1,12,3,8,0,16,10,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,14,9,2,0,0,2,0,0,0,1,3,3,8,5,7,5,7,4,12,11,4,2,2,2,4,7,13,20,502,506,123,117,230,191,149,198,15,14,151,162,89,96,22,22,15,10,2,1,0,0,13,13,2,1,383,438,313,374,19,25,7,8,9,6,6,7,14,14,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,6,7,1,1,1,1,0,0,1,0,1,3,4,3,4,5,2,2,14,7,5,2,4,5,4,2,11,7,725,436,149,100,336,172,240,164,12,9,199,174,146,103,23,17,15,8,4,2,0,0,15,10,1,1,569,409,509,321,31,15,4,6,5,8,5,3,11,15,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,14,3,2,1,1,2,0,0,0,1,6,2,5,0,10,3,4,0,12,3,4,2,5,3,8,3,18,8,650,268,157,69,177,131,316,68,26,9,191,137,127,68,39,15,25,7,0,6,0,0,7,21,10,1,610,267,529,190,29,9,12,2,5,7,9,2,22,16,1,0,4,14,0,0,65,80,163,361

In [10]:
df.tail(5)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
51,ENGLAND,SENEGAL,54%,35%,11%,3,0,04 DEC 2022,20 : 00,Round of 16,...,0,0,10,8,0,0,60,74,230,339
52,JAPAN,CROATIA,35%,51%,14%,1,1,05 DEC 2022,16 : 00,Round of 16,...,0,0,18,11,0,0,100,100,405,308
53,BRAZIL,KOREA REPUBLIC,47%,44%,9%,4,1,05 DEC 2022,20 : 00,Round of 16,...,1,0,10,18,0,0,73,81,310,329
54,MOROCCO,SPAIN,22%,68%,10%,0,0,06 DEC 2022,16 : 00,Round of 16,...,0,0,14,6,0,0,100,66,573,217
55,PORTUGAL,SWITZERLAND,43%,48%,9%,6,1,06 DEC 2022,20 : 00,Round of 16,...,0,0,10,15,0,0,71,54,357,240

In [11]:
df.columns

Index(['team1', 'team2', 'possession team1', 'possession team2',
       'possession in contest', 'number of goals team1',
       'number of goals team2', 'date', 'hour', 'category',
       'total attempts team1', 'total attempts team2', 'conceded team1',
       'conceded team2', 'goal inside the penalty area team1',
       'goal inside the penalty area team2',
       'goal outside the penalty area team1',
       'goal outside the penalty area team2', 'assists team1', 'assists team2',
       'on target attempts team1', 'on target attempts team2',
       'off target attempts team1', 'off target attempts team2',
       'attempts inside the penalty area team1',
       'attempts inside the penalty area  team2',
       'attempts outside the penalty area  team1',
       'attempts outside the penalty area  team2', 'left channel team1',
       'left channel team2', 'left inside channel team1',
       'left inside channel team2', 'central channel team1',
       'central channel team2', 'right inside channel team1',
       'right inside channel team2', 'right channel team1',
       'right channel team2', 'total offers to receive team1',
       'total offers to receive team2', 'inbehind offers to receive team1',
       'inbehind offers to receive team2', 'inbetween offers to receive team1',
       'inbetween offers to receive team2', 'infront offers to receive team1',
       'infront offers to receive team2',
       'receptions between midfield and defensive lines team1',
       'receptions between midfield and defensive lines team2',
       'attempted line breaks team1', 'attempted line breaks team2',
       'completed line breaksteam1', 'completed line breaks team2',
       'attempted defensive line breaks team1',
       'attempted defensive line breaks team2',
       'completed defensive line breaksteam1',
       'completed defensive line breaks team2', 'yellow cards team1',
       'yellow cards team2', 'red cards team1', 'red cards team2',
       'fouls against team1', 'fouls against team2', 'offsides team1',
       'offsides team2', 'passes team1', 'passes team2',
       'passes completed team1', 'passes completed team2', 'crosses team1',
       'crosses team2', 'crosses completed team1', 'crosses completed team2',
       'switches of play completed team1', 'switches of play completed team2',
       'corners team1', 'corners team2', 'free kicks team1',
       'free kicks team2', 'penalties scored team1', 'penalties scored team2',
       'goal preventions team1', 'goal preventions team2', 'own goals team1',
       'own goals team2', 'forced turnovers team1', 'forced turnovers team2',
       'defensive pressures applied team1',
       'defensive pressures applied team2'],
      dtype='object')

In [14]:
df.dtypes

team1                                object
team2                                object
possession team1                     object
possession team2                     object
possession in contest                object
                                      ...
own goals team2                       int64
forced turnovers team1                int64
forced turnovers team2                int64
defensive pressures applied team1     int64
defensive pressures applied team2     int64
Length: 88, dtype: object

In [17]:
df.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,assists team1,assists team2,on target attempts team1,on target attempts team2,off target attempts team1,off target attempts team2,attempts inside the penalty area team1,attempts inside the penalty area team2,attempts outside the penalty area team1,attempts outside the penalty area team2,left channel team1,left channel team2,left inside channel team1,left inside channel team2,central channel team1,central channel team2,right inside channel team1,right inside channel team2,right channel team1,right channel team2,total offers to receive team1,total offers to receive team2,inbehind offers to receive team1,inbehind offers to receive team2,inbetween offers to receive team1,inbetween offers to receive team2,infront offers to receive team1,infront offers to receive team2,receptions between midfield and defensive lines team1,receptions between midfield and defensive lines team2,attempted line breaks team1,attempted line breaks team2,completed line breaksteam1,completed line breaks team2,attempted defensive line breaks team1,attempted defensive line breaks team2,completed defensive line breaksteam1,completed defensive line breaks team2,yellow cards team1,yellow cards team2,red cards team1,red cards team2,fouls against team1,fouls against team2,offsides team1,offsides team2,passes team1,passes team2,passes completed team1,passes completed team2,crosses team1,crosses team2,crosses completed team1,crosses completed team2,switches of play completed team1,switches of play completed team2,corners team1,corners team2,free kicks team1,free kicks team2,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.0,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,1.535714,1.107143,11.017857,11.160714,1.107143,1.535714,1.410714,0.982143,0.107143,0.107143,1.196429,0.750000,4.196429,3.642857,4.607143,5.000000,6.946429,6.946429,4.071429,4.214286,13.767857,13.107143,4.785714,4.214286,4.607143,4.750000,4.392857,4.964286,11.910714,12.392857,601.982143,539.125000,128.321429,118.089286,234.821429,209.785714,238.839286,211.250000,11.214286,10.535714,173.803571,166.696429,114.107143,106.196429,18.500000,18.464286,10.196429,9.803571,1.678571,1.553571,0.035714,0.0,11.910714,12.089286,1.928571,1.928571,510.732143,480.946429,438.035714,409.267857,18.392857,18.089286,4.750000,4.017857,6.571429,6.107143,4.607143,4.357143,13.857143,13.642857,0.107143,0.089286,11.482143,11.232143,0.017857,0.017857,70.785714,70.500000,285.625000,292.607143
std,1.628879,1.056212,5.021738,6.038593,1.056212,1.628879,1.637923,0.999838,0.312094,0.312094,1.432349,0.919486,2.511209,2.665801,2.348528,3.045115,3.909986,4.703653,2.349910,2.774653,6.698687,7.315435,2.534950,3.154877,2.902529,3.004542,2.701371,3.280600,5.471502,6.735735,170.240844,173.054596,33.965280,36.569375,69.447981,59.553708,87.643861,104.299786,5.861164,5.739700,31.498583,28.759137,32.899670,29.207981,6.996103,6.338811,5.794730,5.306667,1.585240,1.263755,0.187256,0.0,4.505660,3.444504,1.787402,1.797545,156.450804,170.779967,159.021664,170.810846,8.355028,7.282050,3.475891,2.323720,3.803621,3.478132,2.883676,2.831181,3.758281,4.494152,0.312094,0.287736,6.134822,5.041613,0.133631,0.133631,14.073462,12.592927,90.911858,80.639417
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,302.000000,212.000000,62.000000,52.000000,106.000000,86.000000,75.000000,68.000000,1.000000,1.000000,104.000000,101.000000,55.000000,45.000000,4.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,3.000000,5.000000,0.000000,0.000000,225.000000,224.000000,167.000000,154.000000,4.000000,5.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,8.000000,5.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,47.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.000000,3.000000,3.000000,4.000000,4.000000,3.000000,2.750000,8.000000,8.000000,3.000000,2.000000,2.000000,3.000000,2.000000,3.000000,9.000000,7.750000,486.500000,434.250000,102.250000,95.000000,180.750000,172.750000,178.000000,155.000000,8.000000,7.000000,153.000000,149.250000,90.500000,85.750000,13.000000,15.000000,7.000000,6.750000,0.000000,1.000000,0.000000,0.0,8.750000,10.000000,1.000000,0.000000,392.750000,389.250000,318.250000,307.500000,12.000000,13.000000,2.750000,2.000000,4.000000,3.000000,2.000000,2.000000,11.000000,10.000000,0.000000,0.000000,7.000000,8.000000,0.000000,0.000000,63.000000,61.000000,226.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,4.000000,3.000000,4.000000,5.000000,6.000000,6.000000,4.000000,4.000000,12.000000,11.000000,5.000000,4.000000,4.000000,4.000000,4.000000,4.000000,11.000000,11.000000,616.000000,538.500000,128.500000,115.000000,232.000000,200.500000,239.500000,186.000000,10.000000,9.000000,173.000000,168.000000,111.000000,99.000000,18.000000,17.000000,8.000000,9.000000,1.000000,1.000000,0.000000,0.0,12.000000,12.000000,2.000000,1.000000,510.000000,449.000000,437.000000,381.500000,18.500000,17.500000,4.000000,4.000000,6.000000,6.000000,5.000000,4.000000,14.000000,14.000000,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,69.500000,72.500000,272.000000,292.500000
75%,2.000000,2.000000,13.250000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,2.000000,1.000000,6.000000,5.000000,6.000000,6.250000,9.250000,9.250000,5.000000,5.000000,17.250000,17.250000,6.000000,6.250000,6.000000,6.000000,6.000000,6.000000,14.250000,17.250000,700.000000,619.250000,153.250000,137.000000,275.250000,259.500000,286.250000,243.000000,15.000000,14.000000,191.500000,185.000000,134.250000,124.500000,23.000000,22.000000,13.000000,12.250000,2.250000,2.000000,0.000000,0.0,15.000000,14.000000,3.000000,3.000000,587.250000,548.000000,518.500000,486.250000,23.000000,22.000000,6.000000,5.000000,9.000000,8.250000,6.000000,6.000000,16.000000,17.000000,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,81.000000,79.250000,325.750000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,6.000000,4.000000,10.000000,13.000000,11.000000,17.000000,18.000000,24.000000,13.000000,15.000000,30.000000,36.000000,12.000000,13.000000,14.000000,16.000000,11.000000,19.000000,27.000000,29.000000,1085.000000,1138.000000,207.000000,217.000000,418.000000,360.000000,487.000000,678.000000,26.000000,28.000000,276.000000,241.000000,233.000000,188.000000,39.000000,37.000000,27.000000,25.000000,7.000000,6.000000,1.000000,0.0,23.000000,21.000000,10.000000,7.000000,1061.000000,1070.000000,1003.000000,992.000000,46.000000,38.000000,17.000000,12.000000,18.000000,14.000000,12.000000,14.000000,23.000000,24.000000,1.000000,1.000000,32.000000,26.000000,1.000000,1.000000,101.000000,101.000000,637.000000,585.000000

Data Preparation